version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=satoru
      - POSTGRES_PASSWORD=satoru
      - POSTGRES_DB=satoru
    ports:
      - 5432:5432
    volumes:
      - /postgres-data:/var/lib/postgresql/data
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jersonsatoru@yahoo.com.br
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 54321:80
    depends_on:
      - psotgres
